/**
 * deploy.ts — deploys all three Anima contracts to Sepolia and writes
 * the deployed addresses back to packages/shared/src/addresses.ts.
 *
 * Usage:
 *   pnpm deploy:sepolia
 *   # → runs: hardhat run scripts/deploy.ts --network sepolia
 *
 * Required env vars (in apps/web/.env.local):
 *   SEPOLIA_RPC_URL        Infura or Alchemy Sepolia endpoint
 *   DEPLOYER_PRIVATE_KEY   0x-prefixed private key with Sepolia ETH
 *   ETHERSCAN_API_KEY      For automatic contract verification
 *
 * The official Zama Wrappers Registry address on Sepolia is read from
 * ZAMA_WRAPPERS_REGISTRY env var, falling back to the known Sepolia address.
 * Source: https://docs.zama.ai/protocol/addresses
 */

import * as fs from 'fs'
import * as path from 'path'
import { ethers, run } from 'hardhat'

// ─── Known Sepolia addresses ──────────────────────────────────────────────────
// Official Zama Wrappers Registry on Sepolia.
// Update once Zama publishes the final mainnet address.
const ZAMA_WRAPPERS_REGISTRY_SEPOLIA =
  process.env.ZAMA_WRAPPERS_REGISTRY ?? '0x0000000000000000000000000000000000000000'

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function verify(address: string, constructorArgs: unknown[]): Promise<void> {
  try {
    console.log(`  ↳ verifying ${address} on Etherscan…`)
    await run('verify:verify', {
      address,
      constructorArguments: constructorArgs,
    })
    console.log(`  ✓ verified`)
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    if (msg.toLowerCase().includes('already verified')) {
      console.log(`  ✓ already verified`)
    } else {
      console.warn(`  ⚠ verification failed: ${msg}`)
    }
  }
}

/** Write deployed addresses back into packages/shared/src/addresses.ts */
function writeAddresses(addresses: {
  animaPayroll: string
  animaRegistryRouter: string
  animaDisperse: string
  zamaWrappersRegistry: string
}): void {
  const outPath = path.resolve(
    __dirname,
    '../../packages/shared/src/addresses.ts',
  )

  const content = `/**
 * Deployed contract addresses on Ethereum Sepolia (chainId 11155111).
 * Auto-generated by contracts/scripts/deploy.ts — DO NOT edit manually.
 * Last deployed: ${new Date().toISOString()}
 */

export const SEPOLIA_CHAIN_ID = 11155111

export const ANIMA_PAYROLL_ADDRESS =
  '${addresses.animaPayroll}' as \`0x\${string}\`

export const ANIMA_REGISTRY_ROUTER_ADDRESS =
  '${addresses.animaRegistryRouter}' as \`0x\${string}\`

export const ANIMA_DISPERSE_ADDRESS =
  '${addresses.animaDisperse}' as \`0x\${string}\`

/**
 * Official Zama Wrappers Registry on Sepolia.
 * Source: https://docs.zama.ai/protocol/addresses
 */
export const ZAMA_WRAPPERS_REGISTRY_ADDRESS =
  '${addresses.zamaWrappersRegistry}' as \`0x\${string}\`

export const CONTRACT_ADDRESSES = {
  animaPayroll:         ANIMA_PAYROLL_ADDRESS,
  animaRegistryRouter:  ANIMA_REGISTRY_ROUTER_ADDRESS,
  animaDisperse:        ANIMA_DISPERSE_ADDRESS,
  zamaWrappersRegistry: ZAMA_WRAPPERS_REGISTRY_ADDRESS,
} as const
`

  fs.writeFileSync(outPath, content, 'utf8')
  console.log(`\n  ✓ addresses written to packages/shared/src/addresses.ts`)
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const [deployer] = await ethers.getSigners()
  const network = await ethers.provider.getNetwork()

  console.log('\n═══════════════════════════════════════════════════════')
  console.log('  Anima — contract deployment')
  console.log('═══════════════════════════════════════════════════════')
  console.log(`  Network:   ${network.name} (chainId ${network.chainId})`)
  console.log(`  Deployer:  ${deployer.address}`)
  console.log(
    `  Balance:   ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH`,
  )
  console.log('───────────────────────────────────────────────────────\n')

  // ── 1. AnimaPayroll ─────────────────────────────────────────────────────────
  console.log('1/3  Deploying AnimaPayroll…')
  const PayrollFactory = await ethers.getContractFactory('AnimaPayroll')
  const payroll = await PayrollFactory.deploy()
  await payroll.waitForDeployment()
  const payrollAddr = await payroll.getAddress()
  console.log(`     ✓ AnimaPayroll deployed at ${payrollAddr}`)

  // ── 2. AnimaRegistryRouter ──────────────────────────────────────────────────
  console.log('\n2/3  Deploying AnimaRegistryRouter…')
  console.log(`     officialRegistry = ${ZAMA_WRAPPERS_REGISTRY_SEPOLIA}`)
  const RouterFactory = await ethers.getContractFactory('AnimaRegistryRouter')
  const router = await RouterFactory.deploy(ZAMA_WRAPPERS_REGISTRY_SEPOLIA)
  await router.waitForDeployment()
  const routerAddr = await router.getAddress()
  console.log(`     ✓ AnimaRegistryRouter deployed at ${routerAddr}`)

  // ── 3. AnimaDisperse ────────────────────────────────────────────────────────
  console.log('\n3/3  Deploying AnimaDisperse…')
  const DisperseFactory = await ethers.getContractFactory('AnimaDisperse')
  const disperse = await DisperseFactory.deploy()
  await disperse.waitForDeployment()
  const disperseAddr = await disperse.getAddress()
  console.log(`     ✓ AnimaDisperse deployed at ${disperseAddr}`)

  // ── Summary ─────────────────────────────────────────────────────────────────
  console.log('\n───────────────────────────────────────────────────────')
  console.log('  Deployment summary')
  console.log('───────────────────────────────────────────────────────')
  console.log(`  AnimaPayroll          ${payrollAddr}`)
  console.log(`  AnimaRegistryRouter   ${routerAddr}`)
  console.log(`  AnimaDisperse         ${disperseAddr}`)
  console.log(`  Zama Registry         ${ZAMA_WRAPPERS_REGISTRY_SEPOLIA}`)

  // ── Write addresses ─────────────────────────────────────────────────────────
  writeAddresses({
    animaPayroll:        payrollAddr,
    animaRegistryRouter: routerAddr,
    animaDisperse:       disperseAddr,
    zamaWrappersRegistry: ZAMA_WRAPPERS_REGISTRY_SEPOLIA,
  })

  // ── Etherscan verification (Sepolia only) ────────────────────────────────────
  if (network.chainId === 11155111n) {
    console.log('\n───────────────────────────────────────────────────────')
    console.log('  Etherscan verification (waiting 6 blocks for indexer…)')
    console.log('───────────────────────────────────────────────────────')

    // Wait ~6 blocks before verifying so Etherscan has indexed the bytecode
    console.log('  waiting for 6 block confirmations…')
    await payroll.deploymentTransaction()?.wait(6)

    await verify(payrollAddr, [])
    await verify(routerAddr, [ZAMA_WRAPPERS_REGISTRY_SEPOLIA])
    await verify(disperseAddr, [])
  }

  console.log('\n═══════════════════════════════════════════════════════')
  console.log('  All done. Update README.md contract addresses table.')
  console.log('═══════════════════════════════════════════════════════\n')
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
