/**
 * redeploy-router.ts
 * Redeploys only AnimaRegistryRouter with the real Zama Wrappers Registry address.
 * AnimaPayroll and AnimaDisperse are already deployed — keep their addresses.
 */
import * as fs from 'fs'
import * as path from 'path'
import { ethers, run } from 'hardhat'
import * as dotenv from 'dotenv'

dotenv.config({ path: '../apps/web/.env.local' })

// Official Zama Wrappers Registry on Sepolia — from @zama-fhe/sdk chain presets
const ZAMA_WRAPPERS_REGISTRY = '0x2f0750Bbb0A246059d80e94c454586a7F27a128e'

// Already deployed — keep these
const PAYROLL_ADDRESS  = '0x86ba59BdC7c6854610892B8a7B76294a94b8d1cB'
const DISPERSE_ADDRESS = '0xdF687b7fD99E9291CD0633F8c122A8ff8712Ab61'

async function main() {
  const [deployer] = await ethers.getSigners()
  const network = await ethers.provider.getNetwork()

  console.log('\n═══════════════════════════════════════════════════════')
  console.log('  AnimaRegistryRouter — redeploy with real Zama registry')
  console.log('═══════════════════════════════════════════════════════')
  console.log(`  Network:          ${network.name} (chainId ${network.chainId})`)
  console.log(`  Deployer:         ${deployer.address}`)
  console.log(`  Balance:          ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH`)
  console.log(`  Zama Registry:    ${ZAMA_WRAPPERS_REGISTRY}`)
  console.log('───────────────────────────────────────────────────────\n')

  const RouterFactory = await ethers.getContractFactory('AnimaRegistryRouter')
  const router = await RouterFactory.deploy(ZAMA_WRAPPERS_REGISTRY)
  await router.waitForDeployment()
  const routerAddr = await router.getAddress()
  console.log(`✓ AnimaRegistryRouter deployed at ${routerAddr}`)

  // Update addresses.ts
  const outPath = path.resolve(__dirname, '../../packages/shared/src/addresses.ts')
  const content = `/**
 * Deployed contract addresses on Ethereum Sepolia (chainId 11155111).
 * Auto-generated by contracts/scripts/redeploy-router.ts
 * Last deployed: ${new Date().toISOString()}
 */

export const SEPOLIA_CHAIN_ID = 11155111

export const ANIMA_PAYROLL_ADDRESS =
  '${PAYROLL_ADDRESS}' as \`0x\${string}\`

export const ANIMA_REGISTRY_ROUTER_ADDRESS =
  '${routerAddr}' as \`0x\${string}\`

export const ANIMA_DISPERSE_ADDRESS =
  '${DISPERSE_ADDRESS}' as \`0x\${string}\`

/**
 * Official Zama Wrappers Registry on Sepolia.
 * Source: @zama-fhe/sdk chain presets (sepolia.registryAddress)
 */
export const ZAMA_WRAPPERS_REGISTRY_ADDRESS =
  '${ZAMA_WRAPPERS_REGISTRY}' as \`0x\${string}\`

export const CONTRACT_ADDRESSES = {
  animaPayroll:         ANIMA_PAYROLL_ADDRESS,
  animaRegistryRouter:  ANIMA_REGISTRY_ROUTER_ADDRESS,
  animaDisperse:        ANIMA_DISPERSE_ADDRESS,
  zamaWrappersRegistry: ZAMA_WRAPPERS_REGISTRY_ADDRESS,
} as const
`
  fs.writeFileSync(outPath, content, 'utf8')
  console.log('✓ packages/shared/src/addresses.ts updated')

  // Etherscan verification
  if (network.chainId === 11155111n) {
    console.log('\nWaiting 6 confirmations for Etherscan…')
    await router.deploymentTransaction()?.wait(6)
    try {
      await run('verify:verify', {
        address: routerAddr,
        constructorArguments: [ZAMA_WRAPPERS_REGISTRY],
      })
      console.log('✓ Verified on Etherscan')
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e)
      console.log(`⚠ Verification: ${msg}`)
    }
  }

  console.log('\n═══════════════════════════════════════════════════════')
  console.log(`  New AnimaRegistryRouter: ${routerAddr}`)
  console.log(`  update README contract table with this address`)
  console.log('═══════════════════════════════════════════════════════\n')
}

main().catch(err => { console.error(err); process.exit(1) })
