/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZamaWrappersRegistry,
  IZamaWrappersRegistryInterface,
} from "../../../src/AnimaRegistryRouter.sol/IZamaWrappersRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "erc20",
        type: "address",
      },
    ],
    name: "getPairByERC20",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "erc20",
            type: "address",
          },
          {
            internalType: "address",
            name: "erc7984",
            type: "address",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "uint8",
            name: "decimals",
            type: "uint8",
          },
        ],
        internalType: "struct IZamaWrappersRegistry.Pair",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "erc7984",
        type: "address",
      },
    ],
    name: "getPairByERC7984",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "erc20",
            type: "address",
          },
          {
            internalType: "address",
            name: "erc7984",
            type: "address",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "uint8",
            name: "decimals",
            type: "uint8",
          },
        ],
        internalType: "struct IZamaWrappersRegistry.Pair",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pairCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "pairs",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "erc20",
            type: "address",
          },
          {
            internalType: "address",
            name: "erc7984",
            type: "address",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "uint8",
            name: "decimals",
            type: "uint8",
          },
        ],
        internalType: "struct IZamaWrappersRegistry.Pair",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZamaWrappersRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IZamaWrappersRegistryInterface {
    return new Interface(_abi) as IZamaWrappersRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZamaWrappersRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IZamaWrappersRegistry;
  }
}
