/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as animaDisperseSol from "./AnimaDisperse.sol";
export * as animaPayrollSol from "./AnimaPayroll.sol";
export * as animaRegistryRouterSol from "./AnimaRegistryRouter.sol";
export * as mocks from "./mocks";
