/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as animaRegistryRouterSol from "./AnimaRegistryRouter.sol";
export * as mocks from "./mocks";
export { AnimaDisperse__factory } from "./AnimaDisperse__factory";
export { AnimaPayroll__factory } from "./AnimaPayroll__factory";
