/**
 * FROZEN backward-compat fixture: a minimal `anima.config.ts` a real user could
 * have written at an OLDER release (v0.5.0-era: only `network` + a handful of
 * fields, NO operator/subname/approvals/sandbox/economy/etc.). The CURRENT
 * `defineConfig` decoder MUST keep resolving this to a fully-defaulted
 * `AnimaConfig`. If a future change makes any of the (then-)optional fields
 * REQUIRED, importing this fixture (or loading it via findAndLoadConfig) fails
 * and CI goes red. Do NOT edit this file — a newer config shape adds a NEW
 * fixture, never mutates this one.
 *
 * Named `*.fixture.ts` (not `anima.config.ts`) because `.gitignore` line 38
 * ignores the literal `anima.config.ts` (it's a real per-user secret). The CLI
 * loader test copies these exact bytes to a temp `anima.config.ts` at runtime
 * to exercise `findAndLoadConfig`'s real filename-based discovery.
 *
 * Imported relatively (not via `@s0nderlabs/anima-core`) so the fixture stays
 * pinned to the in-repo source under test.
 */
import { defineConfig } from '../../../packages/core/src/config'

export default defineConfig({
  network: '0g-mainnet',
})
