/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AnimaDisperse {
  export type VestingScheduleStruct = {
    cliff: BigNumberish;
    linear: BigNumberish;
  };

  export type VestingScheduleStructOutput = [cliff: bigint, linear: bigint] & {
    cliff: bigint;
    linear: bigint;
  };
}

export interface AnimaDisperseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancel"
      | "claim"
      | "claimed"
      | "confidentialProtocolId"
      | "createDistribution"
      | "distributionCount"
      | "distributions"
      | "getAllocation"
      | "getDistribution"
      | "requestDecryptPermit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Cancelled"
      | "Claimed"
      | "DecryptPermitGranted"
      | "DistributionCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish, AddressLike[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createDistribution",
    values: [
      AddressLike,
      AddressLike[],
      BytesLike[],
      BytesLike[],
      AnimaDisperse.VestingScheduleStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "distributionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllocation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistribution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryptPermit",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryptPermit",
    data: BytesLike
  ): Result;
}

export namespace CancelledEvent {
  export type InputTuple = [id: BigNumberish, distributor: AddressLike];
  export type OutputTuple = [id: bigint, distributor: string];
  export interface OutputObject {
    id: bigint;
    distributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [id: BigNumberish, recipient: AddressLike];
  export type OutputTuple = [id: bigint, recipient: string];
  export interface OutputObject {
    id: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptPermitGrantedEvent {
  export type InputTuple = [id: BigNumberish, recipient: AddressLike];
  export type OutputTuple = [id: bigint, recipient: string];
  export interface OutputObject {
    id: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributionCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    distributor: AddressLike,
    token: AddressLike,
    recipientCount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    distributor: string,
    token: string,
    recipientCount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    distributor: string;
    token: string;
    recipientCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnimaDisperse extends BaseContract {
  connect(runner?: ContractRunner | null): AnimaDisperse;
  waitForDeployment(): Promise<this>;

  interface: AnimaDisperseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancel: TypedContractMethod<
    [
      id: BigNumberish,
      recipients: AddressLike[],
      encAmounts: BytesLike[],
      proofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<
    [id: BigNumberish, encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createDistribution: TypedContractMethod<
    [
      token: AddressLike,
      recipients: AddressLike[],
      encAmounts: BytesLike[],
      proofs: BytesLike[],
      vesting: AnimaDisperse.VestingScheduleStruct
    ],
    [bigint],
    "nonpayable"
  >;

  distributionCount: TypedContractMethod<[], [bigint], "view">;

  distributions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        AnimaDisperse.VestingScheduleStructOutput
      ] & {
        token: string;
        distributor: string;
        createdAt: bigint;
        recipientCount: bigint;
        active: boolean;
        vesting: AnimaDisperse.VestingScheduleStructOutput;
      }
    ],
    "view"
  >;

  getAllocation: TypedContractMethod<[id: BigNumberish], [string], "view">;

  getDistribution: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint, bigint] & {
        token: string;
        distributor: string;
        createdAt: bigint;
        recipientCount: bigint;
        active: boolean;
        vestingCliff: bigint;
        vestingLinear: bigint;
      }
    ],
    "view"
  >;

  requestDecryptPermit: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      recipients: AddressLike[],
      encAmounts: BytesLike[],
      proofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [id: BigNumberish, encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createDistribution"
  ): TypedContractMethod<
    [
      token: AddressLike,
      recipients: AddressLike[],
      encAmounts: BytesLike[],
      proofs: BytesLike[],
      vesting: AnimaDisperse.VestingScheduleStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        AnimaDisperse.VestingScheduleStructOutput
      ] & {
        token: string;
        distributor: string;
        createdAt: bigint;
        recipientCount: bigint;
        active: boolean;
        vesting: AnimaDisperse.VestingScheduleStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllocation"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getDistribution"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint, bigint] & {
        token: string;
        distributor: string;
        createdAt: bigint;
        recipientCount: bigint;
        active: boolean;
        vestingCliff: bigint;
        vestingLinear: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestDecryptPermit"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Cancelled"
  ): TypedContractEvent<
    CancelledEvent.InputTuple,
    CancelledEvent.OutputTuple,
    CancelledEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptPermitGranted"
  ): TypedContractEvent<
    DecryptPermitGrantedEvent.InputTuple,
    DecryptPermitGrantedEvent.OutputTuple,
    DecryptPermitGrantedEvent.OutputObject
  >;
  getEvent(
    key: "DistributionCreated"
  ): TypedContractEvent<
    DistributionCreatedEvent.InputTuple,
    DistributionCreatedEvent.OutputTuple,
    DistributionCreatedEvent.OutputObject
  >;

  filters: {
    "Cancelled(uint256,address)": TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;
    Cancelled: TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;

    "Claimed(uint256,address)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "DecryptPermitGranted(uint256,address)": TypedContractEvent<
      DecryptPermitGrantedEvent.InputTuple,
      DecryptPermitGrantedEvent.OutputTuple,
      DecryptPermitGrantedEvent.OutputObject
    >;
    DecryptPermitGranted: TypedContractEvent<
      DecryptPermitGrantedEvent.InputTuple,
      DecryptPermitGrantedEvent.OutputTuple,
      DecryptPermitGrantedEvent.OutputObject
    >;

    "DistributionCreated(uint256,address,address,uint256)": TypedContractEvent<
      DistributionCreatedEvent.InputTuple,
      DistributionCreatedEvent.OutputTuple,
      DistributionCreatedEvent.OutputObject
    >;
    DistributionCreated: TypedContractEvent<
      DistributionCreatedEvent.InputTuple,
      DistributionCreatedEvent.OutputTuple,
      DistributionCreatedEvent.OutputObject
    >;
  };
}
