/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AnimaDisperse } from "./AnimaDisperse";
export type { IFHERC20Transfer } from "./IFHERC20Transfer";
