/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MockZamaWrappersRegistry {
  export type PairStruct = {
    erc20: AddressLike;
    erc7984: AddressLike;
    name: string;
    symbol: string;
    decimals: BigNumberish;
  };

  export type PairStructOutput = [
    erc20: string,
    erc7984: string,
    name: string,
    symbol: string,
    decimals: bigint
  ] & {
    erc20: string;
    erc7984: string;
    name: string;
    symbol: string;
    decimals: bigint;
  };
}

export interface MockZamaWrappersRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPairByERC20"
      | "getPairByERC7984"
      | "pairCount"
      | "pairs"
      | "registerPair"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PairRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getPairByERC20",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairByERC7984",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pairCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "pairs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "registerPair",
    values: [AddressLike, AddressLike, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPairByERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPairByERC7984",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pairCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPair",
    data: BytesLike
  ): Result;
}

export namespace PairRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    erc20: AddressLike,
    erc7984: AddressLike
  ];
  export type OutputTuple = [id: bigint, erc20: string, erc7984: string];
  export interface OutputObject {
    id: bigint;
    erc20: string;
    erc7984: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockZamaWrappersRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MockZamaWrappersRegistry;
  waitForDeployment(): Promise<this>;

  interface: MockZamaWrappersRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPairByERC20: TypedContractMethod<
    [erc20: AddressLike],
    [MockZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  getPairByERC7984: TypedContractMethod<
    [erc7984: AddressLike],
    [MockZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  pairCount: TypedContractMethod<[], [bigint], "view">;

  pairs: TypedContractMethod<
    [id: BigNumberish],
    [MockZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  registerPair: TypedContractMethod<
    [
      erc20: AddressLike,
      erc7984: AddressLike,
      name: string,
      symbol: string,
      decimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPairByERC20"
  ): TypedContractMethod<
    [erc20: AddressLike],
    [MockZamaWrappersRegistry.PairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairByERC7984"
  ): TypedContractMethod<
    [erc7984: AddressLike],
    [MockZamaWrappersRegistry.PairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "pairCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pairs"
  ): TypedContractMethod<
    [id: BigNumberish],
    [MockZamaWrappersRegistry.PairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerPair"
  ): TypedContractMethod<
    [
      erc20: AddressLike,
      erc7984: AddressLike,
      name: string,
      symbol: string,
      decimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PairRegistered"
  ): TypedContractEvent<
    PairRegisteredEvent.InputTuple,
    PairRegisteredEvent.OutputTuple,
    PairRegisteredEvent.OutputObject
  >;

  filters: {
    "PairRegistered(uint256,address,address)": TypedContractEvent<
      PairRegisteredEvent.InputTuple,
      PairRegisteredEvent.OutputTuple,
      PairRegisteredEvent.OutputObject
    >;
    PairRegistered: TypedContractEvent<
      PairRegisteredEvent.InputTuple,
      PairRegisteredEvent.OutputTuple,
      PairRegisteredEvent.OutputObject
    >;
  };
}
