/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockERC7984WrapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balanceOf"
      | "confidentialProtocolId"
      | "decimals"
      | "mint"
      | "mintCallCount"
      | "mintEncrypted"
      | "name"
      | "symbol"
      | "underlying"
      | "unwrap"
      | "unwrapCallCount"
      | "wrap"
      | "wrapCallCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Unwrap" | "Wrap"): EventFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintEncrypted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "underlying",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unwrap",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unwrapCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wrap",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapCallCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "underlying", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unwrap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unwrapCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wrap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wrapCallCount",
    data: BytesLike
  ): Result;
}

export namespace UnwrapEvent {
  export type InputTuple = [user: AddressLike, encAmount: BytesLike];
  export type OutputTuple = [user: string, encAmount: string];
  export interface OutputObject {
    user: string;
    encAmount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WrapEvent {
  export type InputTuple = [user: AddressLike, encAmount: BytesLike];
  export type OutputTuple = [user: string, encAmount: string];
  export interface OutputObject {
    user: string;
    encAmount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockERC7984Wrapper extends BaseContract {
  connect(runner?: ContractRunner | null): MockERC7984Wrapper;
  waitForDeployment(): Promise<this>;

  interface: MockERC7984WrapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balanceOf: TypedContractMethod<[account: AddressLike], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  mint: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintCallCount: TypedContractMethod<[], [bigint], "view">;

  mintEncrypted: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  underlying: TypedContractMethod<[], [string], "view">;

  unwrap: TypedContractMethod<
    [encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  unwrapCallCount: TypedContractMethod<[], [bigint], "view">;

  wrap: TypedContractMethod<
    [encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  wrapCallCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintEncrypted"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "underlying"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unwrap"
  ): TypedContractMethod<
    [encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unwrapCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "wrap"
  ): TypedContractMethod<
    [encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wrapCallCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Unwrap"
  ): TypedContractEvent<
    UnwrapEvent.InputTuple,
    UnwrapEvent.OutputTuple,
    UnwrapEvent.OutputObject
  >;
  getEvent(
    key: "Wrap"
  ): TypedContractEvent<
    WrapEvent.InputTuple,
    WrapEvent.OutputTuple,
    WrapEvent.OutputObject
  >;

  filters: {
    "Unwrap(address,bytes32)": TypedContractEvent<
      UnwrapEvent.InputTuple,
      UnwrapEvent.OutputTuple,
      UnwrapEvent.OutputObject
    >;
    Unwrap: TypedContractEvent<
      UnwrapEvent.InputTuple,
      UnwrapEvent.OutputTuple,
      UnwrapEvent.OutputObject
    >;

    "Wrap(address,bytes32)": TypedContractEvent<
      WrapEvent.InputTuple,
      WrapEvent.OutputTuple,
      WrapEvent.OutputObject
    >;
    Wrap: TypedContractEvent<
      WrapEvent.InputTuple,
      WrapEvent.OutputTuple,
      WrapEvent.OutputObject
    >;
  };
}
