/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMorphoConfidentialVault,
  IMorphoConfidentialVaultInterface,
} from "../../../src/AnimaPayroll.sol/IMorphoConfidentialVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "euint64",
        name: "encAmount",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "depositConfidential",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "euint64",
        name: "encAmount",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "withdrawConfidential",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMorphoConfidentialVault__factory {
  static readonly abi = _abi;
  static createInterface(): IMorphoConfidentialVaultInterface {
    return new Interface(_abi) as IMorphoConfidentialVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMorphoConfidentialVault {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMorphoConfidentialVault;
  }
}
