/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IZamaWrappersRegistry {
  export type PairStruct = {
    erc20: AddressLike;
    erc7984: AddressLike;
    name: string;
    symbol: string;
    decimals: BigNumberish;
  };

  export type PairStructOutput = [
    erc20: string,
    erc7984: string,
    name: string,
    symbol: string,
    decimals: bigint
  ] & {
    erc20: string;
    erc7984: string;
    name: string;
    symbol: string;
    decimals: bigint;
  };
}

export interface AnimaRegistryRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "faucet"
      | "getPair"
      | "getPairByERC20"
      | "getPairByERC7984"
      | "grantDecryptPermit"
      | "officialPairCount"
      | "officialRegistry"
      | "unwrap"
      | "wrap"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptPermitGranted"
      | "Faucet"
      | "Unwrapped"
      | "Wrapped"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "faucet",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPair",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairByERC20",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairByERC7984",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantDecryptPermit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "officialPairCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "officialRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unwrap",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wrap",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "faucet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPairByERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPairByERC7984",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDecryptPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "officialPairCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "officialRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unwrap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wrap", data: BytesLike): Result;
}

export namespace DecryptPermitGrantedEvent {
  export type InputTuple = [user: AddressLike, token: AddressLike];
  export type OutputTuple = [user: string, token: string];
  export interface OutputObject {
    user: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnwrappedEvent {
  export type InputTuple = [
    user: AddressLike,
    pairId: BigNumberish,
    erc7984: AddressLike
  ];
  export type OutputTuple = [user: string, pairId: bigint, erc7984: string];
  export interface OutputObject {
    user: string;
    pairId: bigint;
    erc7984: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WrappedEvent {
  export type InputTuple = [
    user: AddressLike,
    pairId: BigNumberish,
    erc7984: AddressLike
  ];
  export type OutputTuple = [user: string, pairId: bigint, erc7984: string];
  export interface OutputObject {
    user: string;
    pairId: bigint;
    erc7984: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnimaRegistryRouter extends BaseContract {
  connect(runner?: ContractRunner | null): AnimaRegistryRouter;
  waitForDeployment(): Promise<this>;

  interface: AnimaRegistryRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  faucet: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPair: TypedContractMethod<
    [pairId: BigNumberish],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  getPairByERC20: TypedContractMethod<
    [erc20: AddressLike],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  getPairByERC7984: TypedContractMethod<
    [erc7984: AddressLike],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  grantDecryptPermit: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  officialPairCount: TypedContractMethod<[], [bigint], "view">;

  officialRegistry: TypedContractMethod<[], [string], "view">;

  unwrap: TypedContractMethod<
    [pairId: BigNumberish, encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  wrap: TypedContractMethod<
    [pairId: BigNumberish, encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "faucet"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPair"
  ): TypedContractMethod<
    [pairId: BigNumberish],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairByERC20"
  ): TypedContractMethod<
    [erc20: AddressLike],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairByERC7984"
  ): TypedContractMethod<
    [erc7984: AddressLike],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantDecryptPermit"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "officialPairCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "officialRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unwrap"
  ): TypedContractMethod<
    [pairId: BigNumberish, encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wrap"
  ): TypedContractMethod<
    [pairId: BigNumberish, encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DecryptPermitGranted"
  ): TypedContractEvent<
    DecryptPermitGrantedEvent.InputTuple,
    DecryptPermitGrantedEvent.OutputTuple,
    DecryptPermitGrantedEvent.OutputObject
  >;
  getEvent(
    key: "Faucet"
  ): TypedContractEvent<
    FaucetEvent.InputTuple,
    FaucetEvent.OutputTuple,
    FaucetEvent.OutputObject
  >;
  getEvent(
    key: "Unwrapped"
  ): TypedContractEvent<
    UnwrappedEvent.InputTuple,
    UnwrappedEvent.OutputTuple,
    UnwrappedEvent.OutputObject
  >;
  getEvent(
    key: "Wrapped"
  ): TypedContractEvent<
    WrappedEvent.InputTuple,
    WrappedEvent.OutputTuple,
    WrappedEvent.OutputObject
  >;

  filters: {
    "DecryptPermitGranted(address,address)": TypedContractEvent<
      DecryptPermitGrantedEvent.InputTuple,
      DecryptPermitGrantedEvent.OutputTuple,
      DecryptPermitGrantedEvent.OutputObject
    >;
    DecryptPermitGranted: TypedContractEvent<
      DecryptPermitGrantedEvent.InputTuple,
      DecryptPermitGrantedEvent.OutputTuple,
      DecryptPermitGrantedEvent.OutputObject
    >;

    "Faucet(address,address,uint256)": TypedContractEvent<
      FaucetEvent.InputTuple,
      FaucetEvent.OutputTuple,
      FaucetEvent.OutputObject
    >;
    Faucet: TypedContractEvent<
      FaucetEvent.InputTuple,
      FaucetEvent.OutputTuple,
      FaucetEvent.OutputObject
    >;

    "Unwrapped(address,uint256,address)": TypedContractEvent<
      UnwrappedEvent.InputTuple,
      UnwrappedEvent.OutputTuple,
      UnwrappedEvent.OutputObject
    >;
    Unwrapped: TypedContractEvent<
      UnwrappedEvent.InputTuple,
      UnwrappedEvent.OutputTuple,
      UnwrappedEvent.OutputObject
    >;

    "Wrapped(address,uint256,address)": TypedContractEvent<
      WrappedEvent.InputTuple,
      WrappedEvent.OutputTuple,
      WrappedEvent.OutputObject
    >;
    Wrapped: TypedContractEvent<
      WrappedEvent.InputTuple,
      WrappedEvent.OutputTuple,
      WrappedEvent.OutputObject
    >;
  };
}
