/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AnimaRegistryRouter } from "./AnimaRegistryRouter";
export type { IERC7984Wrapper } from "./IERC7984Wrapper";
export type { IZamaWrappersRegistry } from "./IZamaWrappersRegistry";
