/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IZamaWrappersRegistry {
  export type PairStruct = {
    erc20: AddressLike;
    erc7984: AddressLike;
    name: string;
    symbol: string;
    decimals: BigNumberish;
  };

  export type PairStructOutput = [
    erc20: string,
    erc7984: string,
    name: string,
    symbol: string,
    decimals: bigint
  ] & {
    erc20: string;
    erc7984: string;
    name: string;
    symbol: string;
    decimals: bigint;
  };
}

export interface IZamaWrappersRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPairByERC20"
      | "getPairByERC7984"
      | "pairCount"
      | "pairs"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPairByERC20",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairByERC7984",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pairCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "pairs", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "getPairByERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPairByERC7984",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pairCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairs", data: BytesLike): Result;
}

export interface IZamaWrappersRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IZamaWrappersRegistry;
  waitForDeployment(): Promise<this>;

  interface: IZamaWrappersRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPairByERC20: TypedContractMethod<
    [erc20: AddressLike],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  getPairByERC7984: TypedContractMethod<
    [erc7984: AddressLike],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  pairCount: TypedContractMethod<[], [bigint], "view">;

  pairs: TypedContractMethod<
    [id: BigNumberish],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPairByERC20"
  ): TypedContractMethod<
    [erc20: AddressLike],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPairByERC7984"
  ): TypedContractMethod<
    [erc7984: AddressLike],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "pairCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pairs"
  ): TypedContractMethod<
    [id: BigNumberish],
    [IZamaWrappersRegistry.PairStructOutput],
    "view"
  >;

  filters: {};
}
