/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMorphoConfidentialVaultInterface extends Interface {
  getFunction(
    nameOrSignature: "depositConfidential" | "withdrawConfidential"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositConfidential",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawConfidential",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositConfidential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawConfidential",
    data: BytesLike
  ): Result;
}

export interface IMorphoConfidentialVault extends BaseContract {
  connect(runner?: ContractRunner | null): IMorphoConfidentialVault;
  waitForDeployment(): Promise<this>;

  interface: IMorphoConfidentialVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositConfidential: TypedContractMethod<
    [encAmount: BytesLike, receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawConfidential: TypedContractMethod<
    [encAmount: BytesLike, receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositConfidential"
  ): TypedContractMethod<
    [encAmount: BytesLike, receiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawConfidential"
  ): TypedContractMethod<
    [encAmount: BytesLike, receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
