/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AnimaPayroll } from "./AnimaPayroll";
export type { IFHERC20 } from "./IFHERC20";
export type { IMorphoConfidentialVault } from "./IMorphoConfidentialVault";
