/**
 * Deployed contract addresses on Ethereum Sepolia (chainId 11155111).
 * Auto-generated by contracts/scripts/deploy.ts — DO NOT edit manually.
 * Last deployed: 2026-07-08T04:30:01.627Z
 */

export const SEPOLIA_CHAIN_ID = 11155111

export const ANIMA_PAYROLL_ADDRESS =
  '0x86ba59BdC7c6854610892B8a7B76294a94b8d1cB' as `0x${string}`

export const ANIMA_REGISTRY_ROUTER_ADDRESS =
  '0x447356d0825409428F1D90E65e067A3710599f83' as `0x${string}`

export const ANIMA_DISPERSE_ADDRESS =
  '0xdF687b7fD99E9291CD0633F8c122A8ff8712Ab61' as `0x${string}`

/**
 * Official Zama Wrappers Registry on Sepolia.
 * Source: https://docs.zama.ai/protocol/addresses
 */
export const ZAMA_WRAPPERS_REGISTRY_ADDRESS =
  '0x0000000000000000000000000000000000000000' as `0x${string}`

export const CONTRACT_ADDRESSES = {
  animaPayroll:         ANIMA_PAYROLL_ADDRESS,
  animaRegistryRouter:  ANIMA_REGISTRY_ROUTER_ADDRESS,
  animaDisperse:        ANIMA_DISPERSE_ADDRESS,
  zamaWrappersRegistry: ZAMA_WRAPPERS_REGISTRY_ADDRESS,
} as const
