/**
 * Deployed contract addresses on Ethereum Sepolia (chainId 11155111).
 * Auto-generated by contracts/scripts/redeploy-router.ts
 * Last deployed: 2026-07-10T03:41:26.343Z
 */

export const SEPOLIA_CHAIN_ID = 11155111

export const ANIMA_PAYROLL_ADDRESS =
  '0x86ba59BdC7c6854610892B8a7B76294a94b8d1cB' as `0x${string}`

export const ANIMA_REGISTRY_ROUTER_ADDRESS =
  '0xe2574934Bc5fEa0158446e68a3d5AaEBc74838DB' as `0x${string}`

export const ANIMA_DISPERSE_ADDRESS =
  '0xdF687b7fD99E9291CD0633F8c122A8ff8712Ab61' as `0x${string}`

/**
 * Official Zama Wrappers Registry on Sepolia.
 * Source: @zama-fhe/sdk chain presets (sepolia.registryAddress)
 */
export const ZAMA_WRAPPERS_REGISTRY_ADDRESS =
  '0x2f0750Bbb0A246059d80e94c454586a7F27a128e' as `0x${string}`

export const CONTRACT_ADDRESSES = {
  animaPayroll:         ANIMA_PAYROLL_ADDRESS,
  animaRegistryRouter:  ANIMA_REGISTRY_ROUTER_ADDRESS,
  animaDisperse:        ANIMA_DISPERSE_ADDRESS,
  zamaWrappersRegistry: ZAMA_WRAPPERS_REGISTRY_ADDRESS,
} as const
