/**
 * Deployed contract addresses on Ethereum Sepolia (chainId 11155111).
 * Auto-generated by contracts/scripts/deploy.ts — DO NOT edit manually.
 * Last deployed: 2026-07-09T03:01:02.641Z
 */

export const SEPOLIA_CHAIN_ID = 11155111

export const ANIMA_PAYROLL_ADDRESS =
  '0x86ba59BdC7c6854610892B8a7B76294a94b8d1cB' as `0x${string}`

export const ANIMA_REGISTRY_ROUTER_ADDRESS =
  '0xa4F161f54BC0f57b6331309D57b0315139De96a4' as `0x${string}`

export const ANIMA_DISPERSE_ADDRESS =
  '0x20a35EE0Ba03D3B4d3e94A2bb970f5a2B1083d58' as `0x${string}`

/**
 * Official Zama Wrappers Registry on Sepolia.
 * Source: https://docs.zama.ai/protocol/addresses
 */
/**
 * Official Zama Wrappers Registry on Sepolia.
 * Source: https://docs.zama.ai/protocol/addresses
 * Verified in @zama-fhe/sdk/chains: sepolia.registryAddress = 0x2f0750Bbb0A246059d80e94c454586a7F27a128e
 */
export const ZAMA_WRAPPERS_REGISTRY_ADDRESS =
  '0x2f0750Bbb0A246059d80e94c454586a7F27a128e' as `0x${string}`

export const CONTRACT_ADDRESSES = {
  animaPayroll:         ANIMA_PAYROLL_ADDRESS,
  animaRegistryRouter:  ANIMA_REGISTRY_ROUTER_ADDRESS,
  animaDisperse:        ANIMA_DISPERSE_ADDRESS,
  zamaWrappersRegistry: ZAMA_WRAPPERS_REGISTRY_ADDRESS,
} as const
