/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AnimaPayrollInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "earnYield"
      | "getBalance"
      | "getYieldBalance"
      | "grantObserver"
      | "isObserver"
      | "paySalary"
      | "withdraw"
      | "withdrawYield"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ObserverUpdated"
      | "SalaryPaid"
      | "Withdrawal"
      | "YieldDeposited"
      | "YieldWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "earnYield",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getYieldBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantObserver",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "isObserver",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paySalary",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawYield",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "earnYield", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getYieldBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantObserver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isObserver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paySalary", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawYield",
    data: BytesLike
  ): Result;
}

export namespace ObserverUpdatedEvent {
  export type InputTuple = [
    granter: AddressLike,
    observer: AddressLike,
    granted: boolean
  ];
  export type OutputTuple = [
    granter: string,
    observer: string,
    granted: boolean
  ];
  export interface OutputObject {
    granter: string;
    observer: string;
    granted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryPaidEvent {
  export type InputTuple = [
    payer: AddressLike,
    employee: AddressLike,
    token: AddressLike
  ];
  export type OutputTuple = [payer: string, employee: string, token: string];
  export interface OutputObject {
    payer: string;
    employee: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [employee: AddressLike, token: AddressLike];
  export type OutputTuple = [employee: string, token: string];
  export interface OutputObject {
    employee: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldDepositedEvent {
  export type InputTuple = [employee: AddressLike, morphoVault: AddressLike];
  export type OutputTuple = [employee: string, morphoVault: string];
  export interface OutputObject {
    employee: string;
    morphoVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldWithdrawnEvent {
  export type InputTuple = [employee: AddressLike, morphoVault: AddressLike];
  export type OutputTuple = [employee: string, morphoVault: string];
  export interface OutputObject {
    employee: string;
    morphoVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnimaPayroll extends BaseContract {
  connect(runner?: ContractRunner | null): AnimaPayroll;
  waitForDeployment(): Promise<this>;

  interface: AnimaPayrollInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  earnYield: TypedContractMethod<
    [
      token: AddressLike,
      morphoVault: AddressLike,
      encAmount: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<[token: AddressLike], [string], "view">;

  getYieldBalance: TypedContractMethod<[token: AddressLike], [string], "view">;

  grantObserver: TypedContractMethod<
    [observer: AddressLike, granted: boolean],
    [void],
    "nonpayable"
  >;

  isObserver: TypedContractMethod<
    [granter: AddressLike, observer: AddressLike],
    [boolean],
    "view"
  >;

  paySalary: TypedContractMethod<
    [
      token: AddressLike,
      employee: AddressLike,
      encAmount: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [token: AddressLike, encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawYield: TypedContractMethod<
    [
      token: AddressLike,
      morphoVault: AddressLike,
      encAmount: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "earnYield"
  ): TypedContractMethod<
    [
      token: AddressLike,
      morphoVault: AddressLike,
      encAmount: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getYieldBalance"
  ): TypedContractMethod<[token: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantObserver"
  ): TypedContractMethod<
    [observer: AddressLike, granted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isObserver"
  ): TypedContractMethod<
    [granter: AddressLike, observer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "paySalary"
  ): TypedContractMethod<
    [
      token: AddressLike,
      employee: AddressLike,
      encAmount: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [token: AddressLike, encAmount: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawYield"
  ): TypedContractMethod<
    [
      token: AddressLike,
      morphoVault: AddressLike,
      encAmount: BytesLike,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ObserverUpdated"
  ): TypedContractEvent<
    ObserverUpdatedEvent.InputTuple,
    ObserverUpdatedEvent.OutputTuple,
    ObserverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryPaid"
  ): TypedContractEvent<
    SalaryPaidEvent.InputTuple,
    SalaryPaidEvent.OutputTuple,
    SalaryPaidEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "YieldDeposited"
  ): TypedContractEvent<
    YieldDepositedEvent.InputTuple,
    YieldDepositedEvent.OutputTuple,
    YieldDepositedEvent.OutputObject
  >;
  getEvent(
    key: "YieldWithdrawn"
  ): TypedContractEvent<
    YieldWithdrawnEvent.InputTuple,
    YieldWithdrawnEvent.OutputTuple,
    YieldWithdrawnEvent.OutputObject
  >;

  filters: {
    "ObserverUpdated(address,address,bool)": TypedContractEvent<
      ObserverUpdatedEvent.InputTuple,
      ObserverUpdatedEvent.OutputTuple,
      ObserverUpdatedEvent.OutputObject
    >;
    ObserverUpdated: TypedContractEvent<
      ObserverUpdatedEvent.InputTuple,
      ObserverUpdatedEvent.OutputTuple,
      ObserverUpdatedEvent.OutputObject
    >;

    "SalaryPaid(address,address,address)": TypedContractEvent<
      SalaryPaidEvent.InputTuple,
      SalaryPaidEvent.OutputTuple,
      SalaryPaidEvent.OutputObject
    >;
    SalaryPaid: TypedContractEvent<
      SalaryPaidEvent.InputTuple,
      SalaryPaidEvent.OutputTuple,
      SalaryPaidEvent.OutputObject
    >;

    "Withdrawal(address,address)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;

    "YieldDeposited(address,address)": TypedContractEvent<
      YieldDepositedEvent.InputTuple,
      YieldDepositedEvent.OutputTuple,
      YieldDepositedEvent.OutputObject
    >;
    YieldDeposited: TypedContractEvent<
      YieldDepositedEvent.InputTuple,
      YieldDepositedEvent.OutputTuple,
      YieldDepositedEvent.OutputObject
    >;

    "YieldWithdrawn(address,address)": TypedContractEvent<
      YieldWithdrawnEvent.InputTuple,
      YieldWithdrawnEvent.OutputTuple,
      YieldWithdrawnEvent.OutputObject
    >;
    YieldWithdrawn: TypedContractEvent<
      YieldWithdrawnEvent.InputTuple,
      YieldWithdrawnEvent.OutputTuple,
      YieldWithdrawnEvent.OutputObject
    >;
  };
}
