/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as animaRegistryRouterSol from "./AnimaRegistryRouter.sol";
export type { animaRegistryRouterSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { AnimaDisperse } from "./AnimaDisperse";
export type { AnimaPayroll } from "./AnimaPayroll";
