/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as animaDisperseSol from "./AnimaDisperse.sol";
export type { animaDisperseSol };
import type * as animaPayrollSol from "./AnimaPayroll.sol";
export type { animaPayrollSol };
import type * as animaRegistryRouterSol from "./AnimaRegistryRouter.sol";
export type { animaRegistryRouterSol };
import type * as mocks from "./mocks";
export type { mocks };
